from aws_cdk import (
    Stack,
    aws_secretsmanager as secretsmanager,
    CfnOutput,
    RemovalPolicy,
    SecretValue,
)
from constructs import Construct
import json


class SecretsStack(Stack):
    """Secrets Manager secrets for MQTT and InfluxDB credentials.

    SECURITY NOTES:
    - MQTT password must be updated after deployment via AWS Console or update-secrets.sh
    - InfluxDB token is auto-generated using Secrets Manager
    - Secrets are retained on stack deletion to prevent data loss
    """

    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        project_name: str = "edgemind",
        environment: str = "prod",
        **kwargs
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # MQTT credentials secret
        # NOTE: Password MUST be updated after deployment - use update-secrets.sh or AWS Console
        # The password cannot be auto-generated as it's provided by the ProveIT! service
        self.mqtt_secret = secretsmanager.Secret(
            self, "MQTTSecret",
            secret_name=f"{project_name}/mqtt",
            description="MQTT broker credentials - UPDATE PASSWORD AFTER DEPLOYMENT",
            secret_object_value={
                "host": SecretValue.unsafe_plain_text("mqtt://virtualfactory.proveit.services:1883"),
                "port": SecretValue.unsafe_plain_text("1883"),
                "username": SecretValue.unsafe_plain_text("UPDATE_USERNAME"),
                "password": SecretValue.unsafe_plain_text("UPDATE_PASSWORD"),
            },
            removal_policy=RemovalPolicy.RETAIN,
        )

        # InfluxDB credentials secret with auto-generated token
        # The token is securely generated by Secrets Manager
        self.influxdb_secret = secretsmanager.Secret(
            self, "InfluxDBSecret",
            secret_name=f"{project_name}/influxdb",
            description="InfluxDB credentials for EdgeMind factory dashboard",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template=json.dumps({
                    "url": "http://influxdb.edgemind.local:8086",
                    "org": "proveit",
                    "bucket": "factory",
                }),
                generate_string_key="token",
                exclude_punctuation=True,
                password_length=64,
            ),
            removal_policy=RemovalPolicy.RETAIN,
        )

        # Outputs
        CfnOutput(
            self, "MQTTSecretArn",
            value=self.mqtt_secret.secret_arn,
            description="ARN of MQTT credentials secret",
            export_name=f"{project_name}-{environment}-mqtt-secret-arn"
        )

        CfnOutput(
            self, "InfluxDBSecretArn",
            value=self.influxdb_secret.secret_arn,
            description="ARN of InfluxDB credentials secret",
            export_name=f"{project_name}-{environment}-influxdb-secret-arn"
        )

        # Export secret names for easy reference
        CfnOutput(
            self, "MQTTSecretName",
            value=self.mqtt_secret.secret_name,
            description="Name of MQTT credentials secret"
        )

        CfnOutput(
            self, "InfluxDBSecretName",
            value=self.influxdb_secret.secret_name,
            description="Name of InfluxDB credentials secret"
        )
